apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forge
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - notification-serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - notification-deployment.yaml
  - notification-postgres.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml